# Generated by Django 2.0.10 on 2019-01-19 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('recomendation', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('useful', models.IntegerField()),
                ('unuseful', models.IntegerField()),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
