# Generated by Django 2.0.10 on 2019-01-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
